apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-seed
  labels:
    app: go-seed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-seed
    spec:
      containers:
        - image: appscode/go-seed:canary
          name: go-seed
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: go-seed
  labels:
    app: go-seed
spec:
  ports:
  - port: 9844
    protocol: TCP
    targetPort: web
  selector:
    app: go-seed
